version: "3.8"
services:
  # 1. ส่วนของ PHP App (ชื่อ service: app)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www  # เชื่อมไฟล์ในเครื่องเรา (ซ้าย) เข้ากับ Docker (ขวา)
    networks:
      - laravel

  # 2. ส่วนของ Nginx Web Server (ชื่อ service: nginx)
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"  # เข้าเว็บผ่าน Port 8000 (localhost:8000)
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app        # บอกให้รอ PHP (app) รันก่อนค่อยรัน Nginx
    networks:
      - laravel

  # 3. ส่วนของ Database MySQL (ชื่อ service: db)
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql # เก็บข้อมูลถาวร (ปิด docker ข้อมูลไม่หาย)
    networks:
      - laravel

# 4. phpMyAdmin (ตัวจัดการ Database)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-pma
    links:
      - db:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - laravel

# ตั้งค่า Network และ Volume
networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
